AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront distribution for React app on S3

Resources:
  ReactS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: "864546685978-web"
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: "arn:aws:s3:::864546685978-web/*"
            Condition:
              StringEquals:
                "AWS:SourceArn": {"Fn::Sub": "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"}

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: S3OriginAccessControl
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: "864546685978-web.s3.amazonaws.com"
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
            S3OriginConfig: {}
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          MinTTL: 0
          DefaultTTL: 3600
          MaxTTL: 86400
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        WebACLId: arn:aws:wafv2:us-east-1:864546685978:global/webacl/ReactAppACL/d124c49f-bf01-499f-b46c-143e5ca5987e
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        HttpVersion: http2
        IPV6Enabled: true