AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Aa1Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: aa1
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  Bb1Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bb1
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  Cc1Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cc1
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST