AWSTemplateFormatVersion: '2010-09-09'
Description: logger_test Lambda (S3 Source)

Resources:
  LoggerTestLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: logger_test
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::864546685978:role/lambda-execution-role
      Runtime: python3.12
      Code:
        S3Bucket: 864546685978-dev
        S3Key: lambda.zip
      Timeout: 30
